### ISSUE TITLE
Thousand separators

### ISSUE THREAD

**Issue by Alcaro** [FixTweet/FixTweet#148]
https://fxtwitter.com/elonmusk/status/1604617643973124097
![image](https://user-images.githubusercontent.com/5085186/208395983-4d5330dd-e880-4b03-94e5-f9f8b0c1244b.png)

It's hard to get a sense of how many 16098545 votes is. 16 098 545 votes would be much easier to read. (Same for reply/retweet/like count.)

**Comment by dangeredwolf** [comment]
I was originally going to implement it with spaces as you suggested, but I found it actually looked pretty bad with the font that Discord uses, so I ended up opting for English-style with commas instead.
<img width="531" alt="Screenshot 2022-12-22 at 21 02 30" src="https://user-images.githubusercontent.com/2636265/209256227-b7f1ea83-57d5-4a6a-9303-532e79a6d4e9.png">

**Comment by Alcaro** [comment]
Yeah, that looks more like bad kerning than anything intentional. And Twitter itself uses commas for vote counts (but 343.3M for other numbers), so commas are the right call.

Looks good to me, thanks.
