### ISSUE TITLE
No seek bar on d.fx/dl.fx on mobile (android)

### ISSUE THREAD

**Issue by Enakin17** [FixTweet/FixTweet#161]
Hi there,

Don't know if this is a FixTweet thing or a Discord thing, but when using d.fxtwitter.com or dl.fx subdomain my friends and I aren't getting a seek bar on mobile. Shows up fine when using normal fxtwitter.com or even fxtwitter.com/tweet.mp4 which is weird considering d.fx and .mp4 should do the same thing, right?
And I've just now learned that using .com/dir/username and /dl/username also remove the seek bar.
Same story on twittpr.com, weird man.
Really, I'm assuming this is a Discord thing and using this as a warning to anyone that might be confused. :)

**NO SEEK BAR**
![image](https://user-images.githubusercontent.com/34503844/212089999-5a6b0422-9e9b-4ff6-babc-50bf95d66f99.png) 

**SEEK BAR VISIBLE**
![image](https://user-images.githubusercontent.com/34503844/212090120-9e90ce30-e7b2-4668-8b3c-bf9269e8d046.png) ![image](https://user-images.githubusercontent.com/34503844/212090215-2b557b5b-f19a-45e5-9fe4-7a7a2be138d0.png)

**Comment by dangeredwolf** [comment]
This is a Discord Mobile thing, not much I can do, sorry.
