### ISSUE TITLE
Have hyperlink when there is a link in a tweet

### ISSUE THREAD

**Issue by x0rld** [FixTweet/FixTweet#166]
![image](https://user-images.githubusercontent.com/45242856/213003559-0b1e6641-b4e2-4b2b-84d5-e1be6ca74077.png)

it would be nice to have a clickable link

**Comment by dangeredwolf** [comment]
This is something Discord would have to implement as website embeds are currently unable to inject links or other formatting (Discord has a custom Twitter implementation which is how they're able to do it)

**Comment by x0rld** [comment]
oh ok thank for the response
