### ISSUE TITLE
Feature request: Indicate in the API response whether a Tweet is marked NSFW

### ISSUE THREAD

**Issue by TheAppleFreak** [FixTweet/FixTweet#268]
I'm working on an iOS Shortcut to take a link copied via the Twitter app and automatically rewrite it to use fx instead. Since on iOS proxy domains like fx don't open Twitter when you click on them within Discord, I want to be able to use the native Twitter embeds whenever possible (which realistically is text-only posts and single image posts). However, since NSFW images don't create embeds with default Twitter links, it'd be nice to have a way to differentiate between the two via the API to know when I need to use one domain over another.

**Comment by dangeredwolf** [comment]
Certainly. Would just passing through [possibly_sensitive](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/tweet) flag on tweets (which is account-wide) be sufficient?

**Comment by dangeredwolf** [comment]
I'd have to investigate it further but it would also be possible to pass through whether someone manually marked their media as sensitive, which is a different flag, and one that not every NSFW account uses.

**Comment by dangeredwolf** [comment]
Anyway, I've deployed FixTweet now with the `possibly_sensitive` flag now. So let me know if that works!

**Comment by TheAppleFreak** [comment]
`possibly_sensitive` is only true on tweets that won't embed by default? 

Either way, this is helpful. Thank you!

**Comment by dangeredwolf** [comment]
Presumably? Unless Twitter has some other criteria for what to show or not. I'll close the issue for now, but if this isn't sufficient then you can reopen it.

**Comment by TheAppleFreak** [comment]
Sounds like a plan!
