### ISSUE TITLE
FixTweet is currently broken due to Twitter API changes

### ISSUE THREAD

**Issue by Ai-Himmel** [FixTweet/FixTweet#333]
Run `curl https://d.fxtwitter.com/Twitter/status/1601692766257709056 ` would get `Sorry, that Tweet doesn't exist :(`
Running in the browser will redirect to the raw link.

**Comment by inverlock** [comment]
Can confirm I am experiencing this issue with any fxtwitter embed

**Comment by hexa0** [comment]
the same issue has just started happening to me too, probably twitter doing some api nonsense

**Comment by Apocolypto** [comment]
Likewise, I am experiencing the issue on my end as well.

**Comment by dangeredwolf** [comment]
It seems Twitter broke the method we use to acocess the API. Specifically, we were using Twitter API v2 REST conversation API, but the Twitter's apps moved to using GraphQL API some time ago. Now it seems they removed that API, which is really annoying. But by moving to the GraphQL API this will be resolved.

**Comment by dangeredwolf** [comment]
Twitter’s web app also no longer lets you view content when signed out, which is alarming. However, it seems it might not be the full story. I tried seeing if authenticating these requests as a user makes them function, and it seems it still fails to go through. Furthermore, while Twitter made it so you can’t view literally anything, FixTweet’s user API is still working with guest token API. So I’m pretty sure Twitter pushed several changes at once to try to lock down scraping of their API… This will likely not be impossible to work around, but it presents us with quite the challenge…

**Comment by dangeredwolf** [comment]
Yep it seems moving to GraphQL fixes these issues, thank you so much @Wazbat for helping fix our API stack aaaaaaaaa

**Comment by Wazbat** [comment]
Aaaa no problem! I'll try to have a fix ready soon!

**Comment by Mazmol** [comment]
Apparently Elon said this was a temp fix, 
https://twitter.com/TitterDaily/status/1674867516747702277

so don't know if you need to change code or not.

**Comment by Haxorzz** [comment]
Well let's see how temporary this "temporary" fix is.

**Comment by JeremieGiffard** [comment]
API access is now a paid feature 
https://twittercommunity.com/t/announcing-new-access-tiers-for-the-twitter-api/188728

**Comment by allanf181** [comment]
https://cdn.syndication.twimg.com/tweet-result?id=1674865731136020505&lang=en
This endpoint is working for non-NSFW tweets

**Comment by Wazbat** [comment]
I just finished refactoring everything to use the graphQL API, and then an hour later it completely stops working with guest tokens that previously worked fine...

**Comment by EthanC** [comment]
> https://cdn.syndication.twimg.com/tweet-result?id=1674865731136020505&lang=en This endpoint is working for non-NSFW tweets

@allanf181 Do we have something like this for accounts and/or search queries?

**Comment by t-wy** [comment]
That endpoint is for embeds, so seems that for accounts / search there are no embed API alternatives.
Also note that retweet count is not included in that endpoint.

**Comment by rileynull** [comment]
even if no other options open up, that syndication API would be enough for our use case. please don't give up on fixtweet 🙂

**Comment by Wazbat** [comment]
It looks like they changed logged out twitter. It no longer just tells you to login and tries to show the tweet, but the endpoint `https://twitter.com/i/api/graphql/3XDB26fBve-MmjHaWTUZxA/TweetDetail` responds with a 404 and an empty body, even in the browser?

Maybe they'll fix this?

**Comment by Apocolypto** [comment]
vxtwitter seems to work fine at the time of writing this

**Comment by Apocolypto** [comment]
> It looks like they changed logged out twitter. It no longer just tells you to login and tries to show the tweet, but the endpoint `https://twitter.com/i/api/graphql/3XDB26fBve-MmjHaWTUZxA/TweetDetail` responds with a 404 and an empty body, even in the browser?
> 
> Maybe they'll fix this soon?

https://twitter.com/nearcyan/status/1674919375600492546
https://twitter.com/elonmusk/status/1674942336583757825

Musk stated that it'll be unlocked shortly and that "drastic & immediate action was necessary due to EXTREME levels of data scraping."

**Comment by Wazbat** [comment]
> https://twitter.com/nearcyan/status/1674919375600492546 https://twitter.com/elonmusk/status/1674942336583757825

I'm unable to view those tweets on my desktop due to the new rate limits that appeared as of an hour ago lol. Had to use mobile

I'll try to refactor the PR ~~again~~ to use this other endpoint so that we're back with at least basic functionality. This sucks

**Comment by allanf181** [comment]
> > [cdn.syndication.twimg.com/tweet-result?id=1674865731136020505&lang=en](https://cdn.syndication.twimg.com/tweet-result?id=1674865731136020505&lang=en) This endpoint is working for non-NSFW tweets
> 
> @allanf181 Do we have something like this for accounts and/or search queries?

https://syndication.twitter.com/srv/timeline-profile/screen-name/TwitterDev?showReplies=true
there is this one that shows the timeline, but does not give profile details

**Comment by allanf181** [comment]
https://platform.twitter.com/embed/Tweet.html?id=1675187969420828672
it would be interesting to redirect users to the official embed url so they don't need to log into twitter to read it since the embeds are not working

**Comment by slord399** [comment]
I don't know it is temp or not but seems fxtwitter start working again?

**Comment by Wazbat** [comment]
> I don't know it is temp or not but seems fxtwitter start working again?

PR branch was deployed directly. It works for sfw tweets, albeit missing some information that that endpoint does not expose. Going to clean up the messy janky implementation while waiting to see how everything unfolds, to see if the much better graphQL API becomes available

**Comment by t-wy** [comment]
Some summary:
https://cdn.syndication.twimg.com/tweet-result?id={tweet_id} endpoint:
- Accept a Tweet ID
- JSON format if Response Code is not 404
- Tweet Object is in another format
- No retweet count is provided

https://syndication.twitter.com/srv/timeline-profile/screen-name/{handle} endpoint:
- Accept a tweet handle
- HTML format, with JSON response inside a script tag
- Tweet Object is in the same format as the original Guest API

**Comment by Mazmol** [comment]
Works now just a heads up :)

**Comment by Wazbat** [comment]
Seeing how things are playing out I'm kind losing hope that the old endpoints start working again for logged out users

**Comment by cendyne** [comment]
It looks like `created_timestamp` went missing

**Comment by Wazbat** [comment]
> [https://syndication.twitter.com/srv/timeline-profile/screen-name/{handle}](https://syndication.twitter.com/srv/timeline-profile/screen-name/%7Bhandle%7D) endpoint:
> 
> * Accept a Twitter handle
> * HTML format, with JSON response inside a script tag
>   
>   * Tweet Objects are located under `.props.pageProps.timeline.entries`
>     
>     * In the same format as the original Guest API
> * Seems do not support arguments for loading beyond the oldest tweet provided

Welp, looks like this endpoint has stopped working now too. At least the other one still does.... For now...
![image](https://github.com/FixTweet/FixTweet/assets/6253896/bc03c6e3-d3ab-4c7c-98f2-2e5e53715b64)

**Comment by EthanC** [comment]
Lots of good research is being done at https://github.com/zedeus/nitter/issues/919#issuecomment-1619067142

**Comment by EthanC** [comment]
Using research from https://github.com/zedeus/nitter/issues/919#issuecomment-1619067142, it seems we have a new path to getting the data that FixTweet provided.

https://github.com/12joan/twitter-client/blob/main/src/twitter.ts

What are the chances the User and Tweet APIs could be fully re-populated with this approach?

**Comment by dangeredwolf** [comment]
@EthanC It does look very promising that we'll be able to restore functionality 100%, it's just a matter of changing how we request guest tokens (to be more like their method) and migrate to GraphQL endpoints

**Comment by buxy-xyz** [comment]
@dangeredwolf login-only update has been undo'd by twitter, public embeds by twitter.com also work again.
am curious if the public guest endpoint survived. (not syndication)

**Comment by dangeredwolf** [comment]
@buxy-xyz From my understanding, Twitter still removed the conversation api we used before so we still need to move to GraphQL, but tweets appearing while logged out again is at least good news

**Comment by Wazbat** [comment]
@buxy-xyz The entire update hasn't been undone, as you still can't view profiles while logged out, and tweet replies don't show. It's also using a completely diferent endpoint

I've updated the fix PR to use this new endpoint, but user fetching may need another fix

**Comment by dangeredwolf** [comment]
Interestingly the TweetResultByRestId graphql query works logged out using guest token, but dies when logged in, and TweetDetail works logged in but apparently not while logged out...

**Comment by LightShaft** [comment]
I've seen that quoted medias aren't embedded anymore. Should I open another issue ? I thought that the API changes might be at fault so I figured it might be better to directly answer here.

Example here : https://twitter.com/Harada_TEKKEN/status/1676953575342358528
Vx is embedding the video, but not fx. Even the default twitter implementation embeds the quoted video.

**Comment by KonoromiHimaries** [comment]
Why not try use nitter to scrape from thing https://github.com/zedeus/nitter/wiki/Instances

**Comment by buxy-xyz** [comment]
> Why not try use nitter to scrape from working instances https://github.com/zedeus/nitter/wiki/Instances

no, scraping an instance that completely ignores nsfw content is not more suitable than the syndication endpoint fx temporarily uses at the moment.

worth taking a look into the recent commits tho.
https://github.com/zedeus/nitter/commit/0bc3c153d9b38a3c02f321fb64a375fef6b97e8e

**Comment by NicoTheCinderace** [comment]
Surprise! fxtwitter is broken **ONCE AGAIN** thanks to Elon!

**Comment by Haxorzz** [comment]
What'd he do

**Comment by NicoTheCinderace** [comment]
> What'd he do

whenever you try to replace links that go to twitter from x.com to fxtwitter, it reads as follows:

"Sorry, due to Twitter API changes, accessing some tweets is temporarily broken. We'll be back soon!" More API bullshit.

**Comment by Haxorzz** [comment]
Damn. Elon be a hard working API engineer

**Comment by NicoTheCinderace** [comment]
@dangeredwolf @Wazbat 

Tagging you two to let you know about the situation.

**Comment by dangeredwolf** [comment]
@NicoTheCinderace Wait, did Elon change anything else? NSFW Tweets are still broken (sorry), and other Tweets I tried seemed to work okay. Did Twitter/X undo the change? If not, please give me an example URL and I'll see what I can do

**Comment by NicoTheCinderace** [comment]
> @NicoTheCinderace Wait, did Elon change anything else? NSFW Tweets are still broken (sorry), and other Tweets I tried seemed to work okay. Did Twitter/X undo the change? If not, please give me an example URL and I'll see what I can do

Seems like it fixed itself for some of the tweets I tried earlier. I just wish Elon would stop breaking shit so easily.

**Comment by dangeredwolf** [comment]
@NicoTheCinderace lol even before Elon bought Twitter i've noticed Twitter engineers break specific routes (causing them to always return 404 not found) and since Elon this has become way more common

**Comment by dangeredwolf** [comment]
Looking at my Sentry it seems this is the corresponding issue... 
`Cannot read properties of undefined (reading 'media')`
My sourcemaps have unfortunately been broken in Sentry for a while, but maybe Twitter accidentally removed media from the API and fixed it?

But yeah, you can see the time window it was seemingly broken lol
<img width="345" alt="Screenshot 2023-08-13 at 15 58 12" src="https://github.com/FixTweet/FixTweet/assets/2636265/1a0cf01b-3e74-4370-904b-6419955d94cd">

**Comment by TomoSuperFan** [comment]
Okay, today fxtwitter broke again. I have a feeling this is related to Twitter switching to X.com. @dangeredwolf, you have to update before things get worse.

**Comment by NicoTheCinderace** [comment]
> @NicoTheCinderace Wait, did Elon change anything else? NSFW Tweets are still broken (sorry), and other Tweets I tried seemed to work okay. Did Twitter/X undo the change? If not, please give me an example URL and I'll see what I can do

https://fxtwitter.com/Xezeno1/status/1691100785546027008?t=mTtrwksFxgpuhXDWc7CD0A&s=19

Fxtwitter is broken again. You guys need to fix this before it gets worse. @dangeredwolf @Wazbat

**Comment by TomoSuperFan** [comment]
Yeah... Discord depends on it!

**Comment by TomoSuperFan** [comment]
Well, it's fixed!

**Comment by Yay295** [comment]
So do we need an fxx.com now? lol

**Comment by TomoSuperFan** [comment]
I don't know... the Twitter url is still working.

**Comment by jslindgit** [comment]
> https://cdn.syndication.twimg.com/tweet-result?id=1674865731136020505&lang=en This endpoint is working for non-NSFW tweets

This isn't working at all anymore.

**Comment by dangeredwolf** [comment]
Most functionality of FixTweet that was lost has been restored:
-T.co link replacement
-NSFW Tweets
-Tweet translation

The only thing that is still missing is the dynamic colors for Discord embeds, and unfortunately it seems Twitter is not giving out that data on the graphql endpoints, so we might be hosed there. 

Since almost all functionality is back, I'll go ahead and close this specific issue. Feel free to open another issue if you have other issues with any particular tweets!
