### ISSUE TITLE
Inverting Tweet Content and Account

### ISSUE THREAD

**Issue by OshidaBCF** [FixTweet/FixTweet#342]
Currently the Tweet text is show at the top with the account shown bellow

Could it be possible to "invert" the position so that it would look like the normal embed

![image](https://github.com/FixTweet/FixTweet/assets/61458287/00054efe-a214-4ef5-8846-43d1d4a76cd0)

![image](https://github.com/FixTweet/FixTweet/assets/61458287/d9222168-361a-4cff-89f2-a315e2f2069b)

**Comment by dangeredwolf** [comment]
When it comes to video, unfortunately, we are limited in terms of how we can present our embed on Discord. This is a Discord limitation out of our control, embeds on Telegram have the same style as native Twitter embeds.

**Comment by OshidaBCF** [comment]
I see, that's unfortunate
