### ISSUE TITLE
Support for Nitter?

### ISSUE THREAD

**Issue by Wolfy76700** [FixTweet/FixTweet#360]
Could it be possible to add a domain name and path for [Nitter links](https://nitter.net/RobertDaleSmith/status/1690831609195364353), for those of us who avoid the main Twitter interface please?

**Comment by SpyderThingy** [comment]
good point, maybe under /n or n.fxtwitter.com

**Comment by dangeredwolf** [comment]
You can now set a custom base_redirect to automatically redirect incoming fxtwitter.com links to nitter.

`https://fxtwitter.com/set_base_redirect?url=https://nitter.net`

Note: At the time of writing this, nitter.net is down. But you can redirect it to another instance if you prefer.

**Comment by limaceous-bushwhacker** [comment]
Seconded.
