### ISSUE TITLE
Bug Report: Media only Quote retweets fail to embed

### ISSUE THREAD

**Issue by wrennnnnn** [FixTweet/FixTweet#387]
How to recreate: apply fxtwitter or fixupx to a media only quote retweet, while viewing on mobile Discord (haven’t tested PC)

Expected Behavior: the media should embed, along with the text of the tweet that is being quoted.

Observed Behavior: the media fails to embed and the standard text for being a quoted message will apply (QRT of:…)

Example: https://fxtwitter.com/emihead/status/1383303816943050753?s=46

**Comment by dangeredwolf** [comment]
It seems a change I made a few days ago broke this unexpectedly. I've fixed the issue and also added other improvements to the `twitter_card` code (which tells Discord how to render things) to improve other aspects of quote tweets. I also made some improvements to the experience of quote tweets with video as a whole. So hopefully it works better now!

<img width="452" alt="Screenshot 2023-09-12 at 06 01 19" src="https://github.com/FixTweet/FixTweet/assets/2636265/1a8f38ff-724c-455a-ae9c-781190db3b75">
