### ISSUE TITLE
Add fx support for x.com links

### ISSUE THREAD

**Issue by Menelwenn** [FixTweet/FixTweet#411]
Hey, since Twitter's rebranding, Twitter apps copy links in the x.com URL.

Is it possible fx/fxx can be supported? It would people to type the word Twitter entirely on the URL edit (bots cannot be used in DMs/Group Chats)

Thank you!

**Comment by Menelwenn** [comment]
/

**Comment by Menelwenn** [comment]
Forgot the label and I struggle to add one on mobile.. sorry.

**Comment by dangeredwolf** [comment]
Use fixupx.com if you have an x.com link and that should work
