### ISSUE TITLE
Translated tweet embed does not show the tweet in it's original language

### ISSUE THREAD

**Issue by RisingFog** [FixTweet/FixTweet#421]
According to the readme for FixTweet, tweets show translated with the original tweet untranslated below:

![image](https://camo.githubusercontent.com/296768bc8e1381f9c946663d92c170c676e0f1609d03e80996d0239026517a78/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3136353536303735313336333332353935322f313030363333333031313133363130323430302f46697854776565742e706e67)

As of now, the embed looks like the following:

![image](https://github.com/FixTweet/FixTweet/assets/2121359/932b9eb8-e0f2-4cb5-ba03-1e3df2069644)

Is this something that was intentionally changed, and if not, is it possible to add functionality to show the original language within the embed?

**Comment by dangeredwolf** [comment]
Oops, yeah, this is a case of the documentation being outdated. We changed this behavior for embeds as it gets unwieldy very quickly with Tweets that have more than a couple sentences. In Telegram, we actually show both in Instant View as it pops out to another screen and has a lot more room, but the embed preview for it is the same like Discord. We also simply make the assumption that if you're going to go out of your way to tell FixTweet to translate the tweet that most of the time, people just want that preview translated. I suppose if there's demand we could try to show both in tweets that are short enough, but I'm not sure how many people would actually want that.

**Comment by RisingFog** [comment]
That's fair enough, I just wanted to make sure if it was a bug or not. Showing both is definitely a niche use case, but could be useful to double check if the translated message is accurate to the original message. Then again, one could also just click on the link to go to the actual tweet for that I guess.

It's ultimately your call but I'll leave the issue open just in case.

**Comment by dangeredwolf** [comment]
I should probably update the documentation <.<
