### ISSUE TITLE
[API] Error Messages

### ISSUE THREAD

**Issue by SomewhatDamaged** [FixTweet/FixTweet#425]
Error messages (failed to retrieve tweets, or actual server failures) return a 200 status and don't return JSON.

Examples:

https://api.fxtwitter.com/status/1493696926608502784 returns a 200 status and HTML that there is a bug or server error instead of a 500 and JSON.

https://api.fxtwitter.com/status/1493696926608502783 redirects to twitter's website rather than returning a 404 and error JSON.

**Comment by dangeredwolf** [comment]
This is a headache that I'm pretty sure started happening after we moved to GraphQL, so we certainly need to fix this, thanks for the report!
