### ISSUE TITLE
[API] Tweets That Retweet a Deleted Tweet Error

### ISSUE THREAD

**Issue by SomewhatDamaged** [FixTweet/FixTweet#426]
Expected behavior:
`https://api.fxtwitter.com/status/1493696926608502784` should return JSON with some kind of error in the `quote` field to show the quoted tweet is deleted.

Actual behavior:
`https://api.fxtwitter.com/status/1493696926608502784` returns HTML saying there was an error and a 200 status.

```HTML
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta content="FixTweet" property="og:title" />
	<meta content="Owie, you crashed FixTweet :(

This is caused by Twitter API downtime or a new bug. Try again in a little while." property="og:description" />
</head>
<title>:(</title>
<style>
	body {
		font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
		padding: 0 20px;
	}

	h1 {
		font-size: 4em;
		font-weight: 900;
		margin-bottom: 0;
	}

	p {
		font-size: 10px;
		opacity: 0.3;
	}
</style>
</head>

<body>
	<h1>Owie :(</h1>
	<h2>You hit a snag that broke FixTweet. It's not your fault though&mdash;This is usually caused by a Twitter outage
		or a new bug.</h2>
	<p>fixtweet-main-e16bd91-2023-10-15T18:37:00</p>
</body>

</html>
```

I mentioned this URL in https://github.com/FixTweet/FixTweet/issues/425

**Comment by dangeredwolf** [comment]
I fixed the logic so it should always return a JSON response even if not found/server error. Seems it was accidentally broken at some point. Quote will return as `null` in case the Tweet is invalid or did not load. If you have any other issues let me know and feel free to open up another issue if you find anything else!

**Comment by SomewhatDamaged** [comment]
Will do! Thanks for the hard work!
