### ISSUE TITLE
s/e/p not works for x.com on discord

### ISSUE THREAD

**Issue by slord399** [FixTweet/FixTweet#429]
It seems to be it works for twitter.com but not for x.com.
(It failed converting domain if it x.com)

Works: https://twitter.com/username/status/xxxx
Not Works: https://x.com/username/status/xxxx

**Comment by dangeredwolf** [comment]
This is because the find-and-replace only works to convert twitter -> twittpr. It won't work for x.com URLs.

**Comment by slord399** [comment]
then....you should state that to readme.md then everyone be happy.

**Comment by dangeredwolf** [comment]
It already said it did with Twitter links, as in, not with X.com links. It stated previously that your URL would become `twittpr.com`, which could never happen with any other domain. Either way, I changed the language to say `twitter.com` links to add clarity.

**Comment by slord399** [comment]
Thank you, that's much clear and understandable.
