### ISSUE TITLE
Use Hono as a router for regex

### ISSUE THREAD

**Issue by ryoppippi** [FixTweet/FixTweet#451]
https://github.com/FixTweet/FixTweet/blob/main/src/worker.ts#L438-L455

Hono solves this TODO!
https://hono.dev/api/routing#regexp

**Comment by dangeredwolf** [comment]
I actually had planned on migrating to Hono but kept putting it off as I've been dealing with other issues affecting the project <.<

Unfinished branch from May: https://github.com/FixTweet/FixTweet/tree/honojs

**Comment by ryoppippi** [comment]
I will make a PR based on the latest main branch

**Comment by ryoppippi** [comment]
I'm working on, but rewriting to hono is so huge

**Comment by ryoppippi** [comment]
The description of the regex part of TODO did not seem to change in Hono

**Comment by dangeredwolf** [comment]
Yeah, you can probably see why I've been putting it off tbh <.<

**Comment by dangeredwolf** [comment]
I really need to organize and split up parts of worker.ts because it feels overgrown at this point. I also want to add domain-specific routing to make stuff easier to deal with between API and domain (and other future uses). I don't know how much of this I want to do myself right now to avoid trampling on your Hono work

**Comment by ryoppippi** [comment]
As I was working on the implementation of Hono, it occurred to me too that it would be better to split the WORKER.
I think it is better to separate the part that interacts with the user and the part that interacts with twitter.
If you have a suggestion, I'll stop working on it for now.

**Comment by ryoppippi** [comment]
FYI, hono rpc is very good for combining more than 2 workers
https://hono.dev/guides/rpc

**Comment by dangeredwolf** [comment]
Working on Hono rewrite, mostly finished with the core logic itself, still needs unit test rework: #479

**Comment by ryoppippi** [comment]
Nice work!
I stop my work.

**Comment by ryoppippi** [comment]
I'll create some pr for that maybe
