### ISSUE TITLE
Something went wrong when opening link

### ISSUE THREAD

**Issue by rafalohaki** [FixTweet/FixTweet#460]
when i open link i get this error.

![image](https://github.com/FixTweet/FixTweet/assets/20607107/0fb39aa2-2070-4158-98d0-8f5f500b9d4a)

using twitter link is working

**Comment by dangeredwolf** [comment]
Hi, thanks for opening an issue. Can you please provide an example URL where you're encountering this issue so we can triage the issue?

**Comment by rafalohaki** [comment]
I think its problem with referer in the code. When i copy paste link again, its working, because it doesnt have referer in it.

**Comment by rafalohaki** [comment]
https://github.com/FixTweet/FixTweet/assets/20607107/83cd71df-f747-4caf-b983-12a23278d1ef

**Comment by rafalohaki** [comment]
https://github.com/FixTweet/FixTweet/assets/20607107/97c50459-0f9c-4841-9e89-376b4c2e948a

**Comment by rafalohaki** [comment]
here its from original instance to be sure its not my instance problem only
https://github.com/FixTweet/FixTweet/assets/20607107/4b07ddcf-7c0a-4c53-bce8-2f4b9495eecc

**Comment by dangeredwolf** [comment]
I forgot to add the other day, I checked out the web requests that are being sent to Twitter and it does not appear the cross-origin `Referer` is being sent to Twitter when using Chrome or Firefox.

**Comment by rafalohaki** [comment]
![image](https://github.com/FixTweet/FixTweet/assets/20607107/71d2d236-d77c-4616-9aff-dddccebe61bf)
og link headers

![image](https://github.com/FixTweet/FixTweet/assets/20607107/c6ca0850-4772-4548-b7c2-0b43f716b544)
modified link headers by embed tool
