### ISSUE TITLE
Embedding multiple images from quoted tweets is currently broken

### ISSUE THREAD

**Issue by Colorized** [FixTweet/FixTweet#471]
Replicate issue: Find or create a post containing multiple images. Then, find or create a quote post to that post that only contains text. Embed the quote post into Discord through fxtwitter.
Expected behavior: Embed shows the user and text of the quote, the user and text of the post being quoted, and the images of the quoted post.
Resulting behavior: Embed shows the user and text of the quote & the user and text of the post being quoted, but does not embed any of the images in the quoted post.

There are a myriad of other issues regarding media and quotes, but I haven't had the time to thoroughly test them yet. May add more issues about them later

**Comment by dangeredwolf** [comment]
Thanks for the bug report! I have pushed a fix so the multi-image tweet renders correctly within quotes now. If you find any other problematic scenarios feel free to open up another issue!
