### ISSUE TITLE
Fixup does not work anymore in Discord

### ISSUE THREAD

**Issue by Vinsup** [FixTweet/FixTweet#474]
Hi,
Since a couple of days, FixupX does not work anymore in Discord.

I even tried Fxtweet and same problem.

**Comment by YouFoundAlpha** [comment]
It still works for me I've just tried it with both domains

**Comment by Vinsup** [comment]
Actually it seems to be working for tweet with text only.
But tweets with a video embed are not working anymore with fxtwitter.com or FixupX...

**Comment by YouFoundAlpha** [comment]
It seems like video embeds doesn't work

**Comment by dangeredwolf** [comment]
I still appear to be able to use embeds with videos. If you have an example of one that doesn't work, could you please share it to help narrow down where the problem lies?
![image](https://github.com/FixTweet/FixTweet/assets/2636265/826d7a0c-0253-4240-9581-4d5448c77358)

**Comment by evanc577** [comment]
Here is one that doesn't work: https://fxtwitter.com/Vandiril/status/1722396132322447758

![image](https://github.com/FixTweet/FixTweet/assets/14303970/bba5dadd-8b40-441a-9ac4-ad557e185bdb)

**Comment by Vinsup** [comment]
I guess it does not work for long videos like this one : https://fxtwitter.com/Qofficiel/status/1721971747040227421?t=8661yueWl6gT0z8JIzgBaQ&s=19

**Comment by dangeredwolf** [comment]
Thank you very much for the examples! I found that we were limiting the maximum length of a title in a video card to 256 when it should have been 255. I have fixed the bug and will roll out soon alongside some other changes.

**Comment by dangeredwolf** [comment]
I backported the fix from my PR so I could get the fix out faster. The tweets linked should now work (to bypass caching you can add a query string). Let me know if you're still having issues!
![image](https://github.com/FixTweet/FixTweet/assets/2636265/ad470c2b-a067-4040-beba-9b43c6f2a12a)
