### ISSUE TITLE
API 404s from bot, but seems fine in a browser

### ISSUE THREAD

**Issue by Tempystral** [FixTweet/FixTweet#483]
Hi,
I've got a link-sourcing bot which uses FXTwitter and somehow all requests to `api.fxtwitter.com` come back as `404 Not Found`. However, the response json loads just fine in my browser. This was working just fine until about yesterday, but I've made no code changes. Has there been a restriction put in place on certain server hosts or on bots?

Thanks for making this by the way, this API is frankly better than Twitter's was even when it was free.

**Comment by dangeredwolf** [comment]
Hm, do you have a trailing slash after the ID? That's been tripping up embed users as well but I didn't apply the same fixes to the API endpoints. Cause for the most part, it does work. If that's the case, I just fixed it in the commit referencing this issue. If you're still having issues, please let me know and give me an examples of the URL you are sending.

**Comment by dangeredwolf** [comment]
Let me know if you're still having problems, otherwise we can close the issue

**Comment by Tempystral** [comment]
> Let me know if you're still having problems, otherwise we can close the issue

Hi, sorry for the late response. I was having issues with and without the trailing slash but they appear to be resolved now. Thanks, I think whatever you changed must have done it (or it was a fluke and my vps was just being weird). Thanks!
