### ISSUE TITLE
Translations aren't working

### ISSUE THREAD

**Issue by jmctune** [FixTweet/FixTweet#484]
I cannot re-open an existing issue, so making a new issue from https://github.com/FixTweet/FixTweet/issues/435.

Translations don't appear to be working at the moment.

https://fxtwitter.com/DQ_X/status/1722993457654816832/en

Also attempted to bypass the cache as suggested in another post:

https://fxtwitter.com/DQ_X/status/1722993457654816832?qwdq/en

![image](https://github.com/FixTweet/FixTweet/assets/17505625/8f685aee-8560-402f-86c5-e5315b17b130)

**Comment by dangeredwolf** [comment]
I'll go ahead and reopen the original issue #435 for this, thank you!
