### ISSUE TITLE
[Bug?] Profile API endpoint redirected to Twitter unless it's bot UA

### ISSUE THREAD

**Issue by JasonHK** [FixTweet/FixTweet#497]
When accessing the profile API endpoint (for example <https://api.fxtwitter.com/TOBOOKS>), only requests with bot UA will returns a JSON response, others will be redirected to Twitter instead. Is this a intended behaviour?

**Comment by dangeredwolf** [comment]
No, this is not intended behavior and likely broke recently due to an internal rewrite of our router. I'll investigate how this unintentionally broke.

**Comment by dangeredwolf** [comment]
Fixed
