### ISSUE TITLE
How to run this

### ISSUE THREAD

**Issue by vishnu5104** [FixTweet/FixTweet#570]
In the package.json it not showsing any commands ro run the APP

**Comment by dangeredwolf** [comment]
FixTweet is designed for serverless platforms such as Cloudflare Workers, which is free. Please follow the instructions at https://github.com/FixTweet/FixTweet?tab=readme-ov-file#deploy-fixtweet-yourself. If you have any other questions feel free to follow up. Closing this issue as it does not seem there is anything for us to fix at this time.
