### ISSUE TITLE
Twitter's new multi media type attachments don't work with mosaic

### ISSUE THREAD

**Issue by burritosoftware** [FixTweet/FixTweet#97]
[Example tweet](https://twitter.com/BurritoFoxxo/status/1581519132972879872) (when fixed, only shows the GIF in the embed)

For something that combines GIFs and static photos, GIFs should be generated with the static photos alongside. Not sure what to do for videos, because they can be more resource heavy and multiple videos are weird to stitch together.

**Comment by dangeredwolf** [comment]
Mosaic for GIFs and videos are not currently planned (see my notes in #95 for reasoning). Currently videos or GIFs are prioritised over static images. Not sure if the current behavior should be intended or not, however.
